//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Books_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books_Category
    {
        public int Id { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual tblBook tblBook { get; set; }
        public virtual tblCategory tblCategory { get; set; }
    }
}
